train_dataset:
  dataset:
    name: stereo-image-folder
    args:
      root_path: E:/Research/Datasets/iPASSR/train/processed
      repeat: 20
      cache: in_memory
  wrapper:
    name: stereo-sr-implicit-downsampled
    args:
      inp_size: [30, 90]
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: stereo-image-folder
    args:
      root_path: E:/Research/Datasets/iPASSR/val/processed
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: stereo-sr-implicit-downsampled
    args:
      inp_size: [30, 90]
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: stereoinr
  args:
    encoder_spec:
      name: nafnet
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        hidden_list: [256, 256, 256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 1.e-3
epoch_max: 1000
cosine_annealing:
  eta_min: 1.e-7

epoch_val: 5
epoch_save: 100

resume: ./save/stereoinr_07-18/epoch-last.pth