train_dataset:
  dataset:
    name: stereo-image-folders
    args:
      root_path: E:/Research/Datasets/iPASSR/train/kitti
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 160]
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 8

val_dataset:
  dataset:
    name: stereo-image-folders
    args:
      root_path: E:/Research/Datasets/iPASSR/val/kitti
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 160]
      scale_max: 4
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: stereoinr
  args:
    encoder_spec:
      name: ssrtr
      args: 
        window_size: 8
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    dispnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [800, 850, 900, 950]
  gamma: 0.5

use_mixup: False
phase: "train"
epoch_val: 5
epoch_save: 100
save_dir: "save/finetuned"

resume: pretrained_models/ssrtr-lte_pretrained/epoch-last.pth
# resume: save/ssrtr-lte_2024-06-15/epoch-last.pth