train_dataset:
  dataset:
    name: stereo-image-folders
    args:
      # root_path: /media/yi/E/Research/Datasets/Flickr1024/Train
      root_path: E:/Research/Datasets/Flickr1024/Train
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: stereo-image-folders
    args:
      # root_path: /media/yi/E/Research/Datasets/Flickr1024/Validation
      root_path: E:/Research/Datasets/Flickr1024/Validation
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: naflte_ours
  args:
    encoder_spec:
      name: ssrtr
      args: 
        hidden_dim: 128
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 3.e-4
epoch_max: 1000
cosine_annealing:
  eta_min: 1.e-7

  

epoch_val: 5
epoch_save: 100
save_dir: "results"

resume: ~