train_dataset:
  dataset:
    name: stereo-image-folders
    args:
      # root_path: /media/yi/E/Research/Datasets/iPASSR/train/processed
      root_path: E:/Research/Datasets/iPASSR/train/processed
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [24, 96]
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 12

val_dataset:
  dataset:
    name: stereo-image-folders
    args:
      # root_path: /media/yi/E/Research/Datasets/iPASSR/val/processed
      root_path: E:/Research/Datasets/iPASSR/val/processed
      first_k: 20
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [24, 96]
      scale_max: 4
      sample_q: 2304
  batch_size: 12

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: naflte_ours
  args:
    encoder_spec:
      name: ssrtr
      args: 
        hidden_dim: 128
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    dispnet_spec:
      name: mlp
      args:
        out_dim: 2
        hidden_list: [256, 256, 256]
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
# cosine_annealing:
#   eta_min: 1.e-7
multi_step_lr:
  milestones: [50, 200, 400, 600, 800]
  gamma: 0.5

use_mixup: true
phase: "train"
epoch_val: 5
epoch_save: 100
save_dir: "results"

resume: ~
# resume: save/ssrtr-lte_2024-05-27/epoch-last.pth