train_dataset:
  dataset:
    name: stereo-image-folders-sceneflow
    args:
      root_path: E:/Research/Datasets/SceneFlow/flythings
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 160]
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 8

val_dataset:
  dataset:
    name: stereo-image-folders-sceneflow
    args:
      root_path: E:/Research/Datasets/SceneFlow/flythings
      phase: TEST
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 160]
      scale_max: 4
      sample_q: 2304
  batch_size: 8

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: naflte_ours
  args:
    encoder_spec:
      name: ssrtr
      args: 
        window_size: 8
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    dispnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 15
# cosine_annealing:
#   eta_min: 1.e-7
multi_step_lr:
  milestones: [800, 850, 900, 950]
  gamma: 0.5

use_mixup: False
epoch_val: 5
epoch_save: 5
save_dir: "sceneflow_pretrained"

# resume: ~
# resume: save/ssrtr-lte_2024-06-15/epoch-last.pth