train_dataset:
  dataset:
    name: stereo-image-folders-sceneflow
    args:
      root_path: E:/Research/Datasets/SceneFlow/flythings
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 96]
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 12

val_dataset:
  dataset:
    name: stereo-image-folders-sceneflow
    args:
      root_path: E:/Research/Datasets/SceneFlow/flythings
      phase: TEST
      first_k: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-stereo
    args:
      inp_size: [32, 96]
      scale_max: 4
  batch_size: 1


model:
  name: stereoinr
  args:
    encoder_spec:
      name: nafnet
      args:
        dual: true
        no_upsampling: true
        width: 48
        num_blks: 16
        fusion_to: 16
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    dispnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
        act: "sine"
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 15

use_mixup: true
phase: "train"
epoch_val: 5
epoch_save: 5
save_dir: "pretrained_models"

resume: ~
